/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-arguments.h
 #	source generated by 4D Plugin Wizard
 #	Project : arguments
 #	author : miyako
 #	2024/05/27
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ARGUMENTS_H
#define PLUGIN_ARGUMENTS_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"

#import <Foundation/Foundation.h>

#pragma mark -

void Get_command_line(PA_PluginParameters params);

#endif /* PLUGIN_ARGUMENTS_H */
